### PR TITLE
Change package name

### PR DESCRIPTION
**Pull request by khaledk2**
This PR changed the installation package to fix the issue described on https://github.com/IDR/deployment/pull/438

### CODE REVIEW

**Review by sbesson — COMMENTED** [review]
The change itself is very minimal. Do you have a link that explains why this package was superseded by `iptables-nft-services`?

The Molecule tests in this role did not fail when enabling the service but I can reproduce the error in the context of the IDR playbooks Molecule tests. Does that point at something else that the IDR playbooks causing an issue with this component?  

From a quick search I came across https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/configuring_firewalls_and_packet_filters/getting-started-with-nftables_firewall-packet-filters#assembly_migrating-from-iptables-to-nftables_getting-started-with-nftables which points at the fact that these utilities are deprecated in RHEL9.

This might point towards a larger effort of reviewing this role and deciding how to modernize it to work with the latest operating system.

**Review by sbesson — APPROVED** [review]
As indicated in https://github.com/IDR/deployment/pull/440#issuecomment-2467873765, this was successfully deployed on `test125` so this is functional. 

There might be a future maintenance work around modernizing firewall rules but this unblocks the deployment of IDR

**Comment by dominikl** [comment]
👍  Looks good to me too. I've tested the commit previously (cherry-picked from https://github.com/IDR/deployment/pull/438 ) in order to spin up pilot-idr0163.

**Comment by will-moore** [comment]
Is this good to merge now then? Since this is needed for progress on https://github.com/IDR/deployment/pull/441 (which we could maybe try to release next week) it would be good if we can get this in.

**Comment by jburel** [comment]
```Important: iptables-nft packages have been deprecated in Red Hat Enterprise Linux 9.```
So this will need to be reviewed. This is a temporary solution

**Comment by jburel** [comment]
Ticket created https://github.com/ome/ansible-role-iptables-raw/issues/14

**Comment by pwalczysko** [comment]
cosensus 0.5.0 for release

**Comment by pwalczysko** [comment]
> cosensus 0.5.0 for release

No, consensus changed to 0.4.1

**Pull request merged**
