### PR TITLE
service_facts may contain firewalld or firewalld.service

### PR DESCRIPTION
**Pull request by manics**
Bug-fix, tag `0.3.1`

### CODE REVIEW

**Comment by joshmoore** [comment]
Think Travis status is spurious. Change seems ok enough.

**Comment by manics** [comment]
Could it be related to the Travis GitHub app? https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by sbesson** [comment]
Removed the unnecessary `Travis CI branch` additional check for merging this PR from the repo settings. Only the `continuous-integration/travis-ci/pr` check should be required.

**Comment by sbesson** [comment]
For a still unclear reason, it got a notification that the automatic role import triggered by Travis CI has failed. Re triggered the role import manually from the Galaxy UI and version 0.3.1 is now available from Galaxy - https://galaxy.ansible.com/ome/iptables_raw.

**Pull request merged**
